services:
  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: unless-stopped
    command: >
      bash -c "redis-server --appendonly yes "
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  prefect-server:
    command: prefect server start --host 0.0.0.0
    image: prefecthq/prefect:3-python3.12
    ports:
      - "4200:4200"  # API
      - "4300:4300"  # UI
    volumes:
      - prefect_data:/root/.prefect
    environment:
      - PREFECT_LOGGING_LEVEL=DEBUG

  postgres:
   image: postgres:latest
   hostname: postgres
   container_name: postgres
   restart: unless-stopped
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - PGDATA=/var/lib/postgresql/data/pgdata
   ports:
     - "5432:5432"
   volumes:
     - ./data/postgresql:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    volumes:
      - ./data/minio:/data
    command: server --console-address ":9001" /data


volumes:
  prefect_data:
